// Package v1 contains generated Go bindings for the A2A gRPC protocol.
//
// This package is automatically generated by the Alis Build platform from the
// A2A protocol buffer definition and is intended for builders implementing
// production-grade, A2A-compliant agentic systems.
//
// The package includes:
//
//   - protobuf message and enum types for core A2A concepts such as tasks,
//     messages, artifacts, agent cards, authentication, and security schemes
//   - gRPC client and server interfaces for A2AService
//   - generated method metadata used by downstream tooling
//
// The generated surface in this module aligns with the official A2A
// specification published by the A2A project:
// https://github.com/a2aproject/A2A/blob/main/specification/a2a.proto
//
// As with the other generated files in this repository, this package should be
// treated as a generated contract package. Manual edits to generated bindings
// should be made in the source proto and generation pipeline, not in the
// generated outputs.
package v1
